### ISSUE TITLE
Video Calls on (Whatsapp And skype)

### ISSUE THREAD

**Issue by MojiDZ** [mparus/g760_lineageos-14.1#5]
in video calling,i see my friend and i, but in my friend phone just show my profile picture instead of my video

**Comment by mparus** [comment]
in skype works for me without problem, I check this

**Comment by MojiDZ** [comment]
Hi mparus
in Previous Builds I check only Skype worked.
in 20170210 build whatsapp worked too.
very thanks for your work.
